services:
  nginx:
    image: nginx:1.27.0@sha256:0f04e4f646a3f14bf31d8bc8d885b6c951fdcf42589d06845f64d18aec6a3c4d
    ports:
      - "8080:80"
    volumes:
      - ./files/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
    command: [nginx-debug, '-g', 'daemon off;']
  api:
    image: docker-nginx-sandbox-api
    ports:
      - "8000:8000"
    volumes:
      - ./files/api/main.py:/app/src/main.py:ro
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8030:80"
