services:
  nginx:
    image: nginx:1.27.0@sha256:6af79ae5de407283dcea8b00d5c37ace95441fd58a8b1d2aa1ed93f5511bb18c
    ports:
      - "8080:80"
    volumes:
      - ./files/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
    command: [nginx-debug, '-g', 'daemon off;']
  api:
    image: docker-nginx-sandbox-api
    ports:
      - "8000:8000"
    volumes:
      - ./files/api/main.py:/app/src/main.py:ro
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8030:80"
