services:
  nginx:
    image: nginx:1.26.0@sha256:ba9587717b056e1993b051f71cea30ddd5caf09ae2087b1eeb11329f52468e49
    ports:
      - "8080:80"
    volumes:
      - ./files/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
    command: [nginx-debug, '-g', 'daemon off;']
  api:
    image: docker-nginx-sandbox-api
    ports:
      - "8000:8000"
    volumes:
      - ./files/api/main.py:/app/src/main.py:ro
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8030:80"
