name: test

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint debian
        uses: hadolint/hadolint-action@d292784f8f3eacda47060b259a580467b0ba410c
        with:
          dockerfile: templates/Dockerfile
          config: .hadolint.yml
      # - name: Set up Python 3.12
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.12"
      #     cache: "pipenv"
      # - name: Install pipenv
      #   run: pip install pipenv
      # - name: Sync
      #   run: pipenv sync --dev
      # - name: Build
      #   run: pipenv run bin/build.sh 3
